name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    - name: Install Linux Dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          libgl1-mesa-dev \
          libfreetype-dev

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        sudo apt-get install --no-install-recommends valgrind
